services:
  db:
    image: postgres:16-alpine
    container_name: turfx_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: turfx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pavansai2205/turfx-backend:latest
    container_name: turfx_backend
    restart: always
    environment:
      DJANGO_SECRET_KEY: django-development-secret-key
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/turfx
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pavansai2205/turfx-frontend:latest
    container_name: turfx_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
