# Generated by Django 5.1.15 on 2026-09-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='turfs.turf'),
        ),
    ]
